# Generated by Django 4.2.5 on 2023-09-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
