# Generated by Django 4.2.5 on 2023-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_auction_active_auction_ask_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imgUrl',
            field=models.ImageField(upload_to='auction_images/'),
        ),
    ]
