# Generated by Django 4.2.5 on 2023-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_imgurl_auction_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='auction_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='img',
        ),
        migrations.AddField(
            model_name='auction',
            name='images',
            field=models.ManyToManyField(to='auctions.image'),
        ),
    ]
