# Generated by Django 4.2.5 on 2023-10-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_image_remove_auction_img_auction_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
    ]
