# Generated by Django 4.2.5 on 2023-10-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='valuta',
            field=models.CharField(choices=[('$', '$ USD'), ('€', '€ EUR'), ('£', '£ GBP'), ('¥', '¥ JPY')], default='$', max_length=5),
        ),
    ]
