# Generated by Django 4.2.5 on 2023-10-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_amount_bid_listing_bid_timestamp_bid_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='valuta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids_valuta', to='auctions.auction'),
        ),
    ]
