# Generated by Django 4.2.5 on 2023-10-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_valuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='valuta',
        ),
    ]
