# Generated by Django 4.2.5 on 2023-10-04 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='auction',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
