# Generated by Django 4.2.5 on 2023-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auction_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='closed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
